services:
  fastapi_api:
    build:
      context: ../../
      dockerfile: ./code/deployment/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models
      
  gradio_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    depends_on:
      - fastapi_api
